// <auto-generated />
using System;
using FindeterApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindeterApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805201457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindeterApp.Models.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdequateAccommodationForDisplacedWorkers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedByNaturalEvents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowsNonDiscriminatoryHiring")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AreSocioEnvironmentalStudiesPublic")
                        .HasColumnType("bit");

                    b.Property<string>("AvoidsAirPollution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsCollectiveDismissals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsExcessiveNoise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsFreshwaterUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsHazardousChemicals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsInfrastructureDismantling")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsUnpleasantOdors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsUnqualifiedSecurity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidsVehicleMovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COVID19PreventionMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClimateChangeAdaptationMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommunicatesSocioEnvironmentalIssues")
                        .HasColumnType("bit");

                    b.Property<string>("CommunitySocializationMechanisms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompliesWithIndividualDismissalLaws")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CompliesWithLaborRegulations")
                        .HasColumnType("bit");

                    b.Property<bool>("ConductsEnvironmentalSupervision")
                        .HasColumnType("bit");

                    b.Property<string>("ConductsHealthAndSafetyInspections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsidersHistoricalPollution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EfficiencyIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergyEfficiencyMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnergySource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EqualConditionsForForeignWorkers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedExecutionTime")
                        .HasColumnType("int");

                    b.Property<string>("GeneratesHazardousWaste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneratesImpactOnFloraFauna")
                        .HasColumnType("bit");

                    b.Property<bool>("GeneratesImpactOnWaterAirSoil")
                        .HasColumnType("bit");

                    b.Property<string>("GeneratesOrdinaryWaste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneratesSocialLaborImpact")
                        .HasColumnType("bit");

                    b.Property<string>("GeneratesWastewater")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasASPersonnel")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeenSanctioned")
                        .HasColumnType("bit");

                    b.Property<string>("HasCommunityComplaintMechanism")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasComplaintMechanism")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEnvironmentalDepartment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEnvironmentalLegalMatrix")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEnvironmentalLiabilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEnvironmentalManagementPlan")
                        .HasColumnType("bit");

                    b.Property<bool>("HasEnvironmentalPolicies")
                        .HasColumnType("bit");

                    b.Property<bool>("HasISO14001Certification")
                        .HasColumnType("bit");

                    b.Property<string>("HasTrainingPrograms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IdentifiesEmergencySituations")
                        .HasColumnType("bit");

                    b.Property<bool>("IdentifiesPreventsImpacts")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesExcludedActivities")
                        .HasColumnType("bit");

                    b.Property<string>("IntegratesCleanProduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConsultationRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LandUse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LightingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagesChildLaborRisks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasuresCarbonFootprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasuresWaterFootprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoForcedLabor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherResourceEfficiencyMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectInfluenceZones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectProgressPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ProjectZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvidesEqualEmploymentOpportunities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReceivedCommunityComplaints")
                        .HasColumnType("bit");

                    b.Property<string>("RecordsWorkplaceAccidents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReducesGHGEmissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportsHealthAndSafetyIncidents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiresChemicalProducts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresEnvironmentalDiagnosis")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresEnvironmentalLicense")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresEnvironmentalPermissions")
                        .HasColumnType("bit");

                    b.Property<string>("RequiresQuarryMaterials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceUsage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespectsUnionAgreements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityPersonnelTrained")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemporaryWorkersEarnMinimumWage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalIntervenedArea")
                        .HasColumnType("float");

                    b.Property<decimal>("TotalProjectValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsesEmissionGeneratingEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsesPesticides")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsesWorkPermitsForHazardousTasks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiesWorkerAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterEfficiencyMeasures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerWaterSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkersCanExpressConcerns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkersKnowTheirRights")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoanApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
